Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
Traceback (most recent call last):
  File "/home/v16b915/calcpi/python/calculatePiMPI.py", line 7, in <module>
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
    size = comm.Get_size()
           ^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 82, in mpi4py.MPI.Comm.Get_size
mpi4py.MPI.Exception: MPI_ERR_COMM: invalid communicator
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[52248,1],59]
  Exit code:    1
--------------------------------------------------------------------------
